env:
  CARGO_INCREMENTAL: '0'
  CARGO_NET_RETRY: '10'
  RUSTUP_MAX_RETRIES: '10'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        targets: x86_64-pc-windows-msvc
    - name: Remove .cargo/config.toml
      run: rm -f .cargo/config.toml .cargo/config
    - name: Build release binary
      run: cargo build --release --target x86_64-pc-windows-msvc --no-default-features
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-windows-x86_64
        path: target/x86_64-pc-windows-msvc/release/${{ github.event.repository.name
          }}.exe
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/x86_64-pc-windows-msvc/release/${{ github.event.repository.name
          }}.exe
        make_latest: false
        name: Latest windows-x86_64
        prerelease: true
        tag_name: latest-windows-x86_64
name: Release windows-x86_64
'on':
  push:
    branches:
    - release
  workflow_dispatch: {}
permissions:
  contents: write
